/**
 * Facility Icon Mappings
 * 
 * This file is auto-generated by:
 * - npm run icons (from types/index.ts)
 * - npm run add-icon <icon-name>
 * 
 * DO NOT EDIT MANUALLY
 * 
 * Static imports required for Metro bundler compatibility.
 * Dynamic imports with template literals are not supported.
 */

import React from 'react';
import CouchIcon from '@/components/icons/cil/couch';
import BaselineWhatsappIcon from '@/components/icons/ic/baseline-whatsapp';
import RoundTvIcon from '@/components/icons/ic/round-tv';
import AcUnitIcon from '@/components/icons/material-symbols/ac-unit';
import BedIcon from '@/components/icons/material-symbols/bed';
import BookmarkIcon from '@/components/icons/material-symbols/bookmark';
import ChairIcon from '@/components/icons/material-symbols/chair';
import ChatIcon from '@/components/icons/material-symbols/chat';
import CloseIcon from '@/components/icons/material-symbols/close';
import DeskIcon from '@/components/icons/material-symbols/desk';
import DirectionsCarIcon from '@/components/icons/material-symbols/directions-car';
import DoorOpenIcon from '@/components/icons/material-symbols/door-open';
import FlashOnIcon from '@/components/icons/material-symbols/flash-on';
import ForkSpoonIcon from '@/components/icons/material-symbols/fork-spoon';
import HomeIcon from '@/components/icons/material-symbols/home';
import KitchenIcon from '@/components/icons/material-symbols/kitchen';
import LaundryIcon from '@/components/icons/material-symbols/laundry';
import LocalLaundryServiceIcon from '@/components/icons/material-symbols/local-laundry-service';
import LocationOnIcon from '@/components/icons/material-symbols/location-on';
import ModeFanIcon from '@/components/icons/material-symbols/mode-fan';
import MosqueIcon from '@/components/icons/material-symbols/mosque';
import PersonIcon from '@/components/icons/material-symbols/person';
import SecurityIcon from '@/components/icons/material-symbols/security';
import SensorDoorOutlineIcon from '@/components/icons/material-symbols/sensor-door-outline';
import SettingsIcon from '@/components/icons/material-symbols/settings';
import ShowerIcon from '@/components/icons/material-symbols/shower';
import TvIcon from '@/components/icons/material-symbols/tv';
import TwoWheelerIcon from '@/components/icons/material-symbols/two-wheeler';
import WaterDropIcon from '@/components/icons/material-symbols/water-drop';
import WaterHeaterIcon from '@/components/icons/material-symbols/water-heater';
import WifiIcon from '@/components/icons/material-symbols/wifi';
import WindowIcon from '@/components/icons/material-symbols/window';
import ToiletIcon from '@/components/icons/mdi/toilet';
import ShelfIcon from '@/components/icons/streamline/shelf';

/**
 * Map of icon names to their components
 * Supports both 'collection:icon-name' and 'icon-name' formats
 */
export const FACILITY_ICON_MAP: Record<string, React.ComponentType<any>> = {
  'cil:couch': CouchIcon,
  'couch': CouchIcon, // backward compat
  'ic:baseline-whatsapp': BaselineWhatsappIcon,
  'baseline-whatsapp': BaselineWhatsappIcon, // backward compat
  'ic:round-tv': RoundTvIcon,
  'round-tv': RoundTvIcon, // backward compat
  'material-symbols:ac-unit': AcUnitIcon,
  'ac-unit': AcUnitIcon, // backward compat
  'material-symbols:bed': BedIcon,
  'bed': BedIcon, // backward compat
  'material-symbols:bookmark': BookmarkIcon,
  'bookmark': BookmarkIcon, // backward compat
  'material-symbols:chair': ChairIcon,
  'chair': ChairIcon, // backward compat
  'material-symbols:chat': ChatIcon,
  'chat': ChatIcon, // backward compat
  'material-symbols:close': CloseIcon,
  'close': CloseIcon, // backward compat
  'material-symbols:desk': DeskIcon,
  'desk': DeskIcon, // backward compat
  'material-symbols:directions-car': DirectionsCarIcon,
  'directions-car': DirectionsCarIcon, // backward compat
  'material-symbols:door-open': DoorOpenIcon,
  'door-open': DoorOpenIcon, // backward compat
  'material-symbols:flash-on': FlashOnIcon,
  'flash-on': FlashOnIcon, // backward compat
  'material-symbols:fork-spoon': ForkSpoonIcon,
  'fork-spoon': ForkSpoonIcon, // backward compat
  'material-symbols:home': HomeIcon,
  'home': HomeIcon, // backward compat
  'material-symbols:kitchen': KitchenIcon,
  'kitchen': KitchenIcon, // backward compat
  'material-symbols:laundry': LaundryIcon,
  'laundry': LaundryIcon, // backward compat
  'material-symbols:local-laundry-service': LocalLaundryServiceIcon,
  'local-laundry-service': LocalLaundryServiceIcon, // backward compat
  'material-symbols:location-on': LocationOnIcon,
  'location-on': LocationOnIcon, // backward compat
  'material-symbols:mode-fan': ModeFanIcon,
  'mode-fan': ModeFanIcon, // backward compat
  'material-symbols:mosque': MosqueIcon,
  'mosque': MosqueIcon, // backward compat
  'material-symbols:person': PersonIcon,
  'person': PersonIcon, // backward compat
  'material-symbols:security': SecurityIcon,
  'security': SecurityIcon, // backward compat
  'material-symbols:sensor-door-outline': SensorDoorOutlineIcon,
  'sensor-door-outline': SensorDoorOutlineIcon, // backward compat
  'material-symbols:settings': SettingsIcon,
  'settings': SettingsIcon, // backward compat
  'material-symbols:shower': ShowerIcon,
  'shower': ShowerIcon, // backward compat
  'material-symbols:tv': TvIcon,
  'tv': TvIcon, // backward compat
  'material-symbols:two-wheeler': TwoWheelerIcon,
  'two-wheeler': TwoWheelerIcon, // backward compat
  'material-symbols:water-drop': WaterDropIcon,
  'water-drop': WaterDropIcon, // backward compat
  'material-symbols:water-heater': WaterHeaterIcon,
  'water-heater': WaterHeaterIcon, // backward compat
  'material-symbols:wifi': WifiIcon,
  'wifi': WifiIcon, // backward compat
  'material-symbols:window': WindowIcon,
  'window': WindowIcon, // backward compat
  'mdi:toilet': ToiletIcon,
  'toilet': ToiletIcon, // backward compat
  'streamline:shelf': ShelfIcon,
  'shelf': ShelfIcon, // backward compat
};

/**
 * Get icon component by name with fallback
 * @param iconName - Format: 'collection:icon-name' or 'icon-name'
 * @returns Icon component or default fallback
 */
export function getFacilityIcon(iconName: string): React.ComponentType<any> {
  // Try with full name first
  if (FACILITY_ICON_MAP[iconName]) {
    return FACILITY_ICON_MAP[iconName];
  }
  
  // Try adding default collection prefix
  const withPrefix = iconName.includes(':') 
    ? iconName 
    : `material-symbols:${iconName}`;
  
  if (FACILITY_ICON_MAP[withPrefix]) {
    return FACILITY_ICON_MAP[withPrefix];
  }
  
  // Fallback to first available icon or placeholder
  const firstIcon = Object.values(FACILITY_ICON_MAP)[0];
  console.warn(`Icon not found: ${iconName}, using fallback`);
  return firstIcon;
}
