#!/usr/bin/env node

/**
 * Add Monicon Icon Script
 *
 * Usage:
 *   npm run add-icon material-symbols:account-box
 *   npm run add-icon lucide:wifi
 *   npm run add-icon toilet  (defaults to material-symbols)
 *
 * This script:
 * 1. Adds icon to monicon.config.ts
 * 2. Generates import in lib/facilityIcons.ts
 * 3. Keeps existing icons intact
 */

const fs = require('fs');
const path = require('path');

// Get icon from command line argument
const iconArg = process.argv[2];

if (!iconArg) {
  console.error('❌ Error: Icon name required');
  console.log('\nUsage:');
  console.log('  npm run add-icon material-symbols:account-box');
  console.log('  npm run add-icon lucide:wifi');
  console.log('  npm run add-icon toilet  (defaults to material-symbols)');
  process.exit(1);
}

// Parse collection and icon name
let collection, iconName, fullIconName;

if (iconArg.includes(':')) {
  [collection, iconName] = iconArg.split(':');
  fullIconName = `${collection}:${iconName}`;
} else {
  collection = 'material-symbols';
  iconName = iconArg;
  fullIconName = `material-symbols:${iconArg}`;
}

console.log(`\n🎨 Adding icon: ${fullIconName}`);

// Paths
const configPath = path.join(__dirname, '..', 'monicon.config.ts');
const facilityIconsPath = path.join(__dirname, '..', 'lib', 'facilityIcons.ts');

// Read existing monicon.config.ts
let existingIcons = [];
if (fs.existsSync(configPath)) {
  const configContent = fs.readFileSync(configPath, 'utf8');
  const match = configContent.match(/icons:\s*\[([\s\S]*?)\]/);
  if (match) {
    existingIcons = match[1]
      .split(',')
      .map((s) => s.trim().replace(/['"]/g, ''))
      .filter((s) => s.length > 0);
  }
}

// Check if icon already exists
if (existingIcons.includes(fullIconName)) {
  console.log(`⚠️  Icon already exists: ${fullIconName}`);
  console.log('✓ No changes needed');
  process.exit(0);
}

// Add new icon
existingIcons.push(fullIconName);
existingIcons.sort(); // Keep alphabetically sorted

// Generate new monicon.config.ts
const newConfig = `import { reactNative, clean } from '@monicon/core/plugins';
import { MoniconConfig } from '@monicon/core';

export default {
  // Auto-generated icon list
  // - Icons from types/index.ts (facility constants)
  // - Icons from 'npm run add-icon' (preserved during regeneration)
  // Run 'npm run icons' to regenerate after updating types/index.ts
  // Format: 'collection:icon-name' (e.g., 'lucide:home', 'material-symbols:wifi')
  icons: [
${existingIcons.map((icon) => `    '${icon}',`).join('\n')}
  ],

  plugins: [
    // Clean output folder before generation
    clean({ patterns: ['components/icons'] }),

    // Generate React Native components
    reactNative({ outputPath: 'components/icons' }),
  ],
} satisfies MoniconConfig;
`;

fs.writeFileSync(configPath, newConfig);
console.log('✓ Updated monicon.config.ts');

// Generate lib/facilityIcons.ts
const iconsByCollection = {};

existingIcons.forEach((icon) => {
  const [col, name] = icon.includes(':') ? icon.split(':') : ['material-symbols', icon];

  if (!iconsByCollection[col]) {
    iconsByCollection[col] = [];
  }
  iconsByCollection[col].push(name);
});

// Generate imports
let imports = [];
let mapEntries = [];

Object.entries(iconsByCollection).forEach(([col, icons]) => {
  icons.forEach((name) => {
    const componentName =
      name
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('') + 'Icon';

    const fullName = `${col}:${name}`;

    imports.push(`import ${componentName} from '@/components/icons/${col}/${name}';`);
    mapEntries.push(`  '${fullName}': ${componentName},`);

    // Add backward compatibility entry (unprefixed)
    mapEntries.push(`  '${name}': ${componentName}, // backward compat`);
  });
});

const facilityIconsContent = `/**
 * Facility Icon Mappings
 * 
 * This file is auto-generated by:
 * - npm run icons (from types/index.ts)
 * - npm run add-icon <icon-name>
 * 
 * DO NOT EDIT MANUALLY
 * 
 * Static imports required for Metro bundler compatibility.
 * Dynamic imports with template literals are not supported.
 */

import React from 'react';
${imports.join('\n')}

/**
 * Map of icon names to their components
 * Supports both 'collection:icon-name' and 'icon-name' formats
 */
export const FACILITY_ICON_MAP: Record<string, React.ComponentType<any>> = {
${mapEntries.join('\n')}
};

/**
 * Get icon component by name with fallback
 * @param iconName - Format: 'collection:icon-name' or 'icon-name'
 * @returns Icon component or default fallback
 */
export function getFacilityIcon(iconName: string): React.ComponentType<any> {
  // Try with full name first
  if (FACILITY_ICON_MAP[iconName]) {
    return FACILITY_ICON_MAP[iconName];
  }
  
  // Try adding default collection prefix
  const withPrefix = iconName.includes(':') 
    ? iconName 
    : \`material-symbols:\${iconName}\`;
  
  if (FACILITY_ICON_MAP[withPrefix]) {
    return FACILITY_ICON_MAP[withPrefix];
  }
  
  // Fallback to first available icon or placeholder
  const firstIcon = Object.values(FACILITY_ICON_MAP)[0];
  console.warn(\`Icon not found: \${iconName}, using fallback\`);
  return firstIcon;
}
`;

fs.writeFileSync(facilityIconsPath, facilityIconsContent);
console.log('✓ Updated lib/facilityIcons.ts');

// Show summary
const collections = Object.keys(iconsByCollection);
console.log('\n📊 Summary:');
console.log(`   Total icons: ${existingIcons.length}`);
console.log(`   Collections: ${collections.join(', ')}`);
console.log(`   New icon: ${fullIconName}`);

console.log('\n✅ Done! Restart your dev server to see changes.');
console.log('   npm run dev\n');
