#!/usr/bin/env node
/**
 * Auto-generate Monicon config and facility icon mapping from types/index.ts
 * Usage: node scripts/generate-icons.js
 *
 * Supports multiple icon collections:
 * - Format: 'collection:icon-name' (e.g., 'material-symbols:toilet', 'lucide:home')
 * - Default collection: 'material-symbols' (if no prefix)
 */

const fs = require('fs');
const path = require('path');

// Read types/index.ts
const typesPath = path.join(__dirname, '../types/index.ts');
const typesContent = fs.readFileSync(typesPath, 'utf-8');

// Read existing icons from monicon.config.ts (preserve add-icon additions)
const configPath = path.join(__dirname, '../monicon.config.ts');
const iconSet = new Set();

if (fs.existsSync(configPath)) {
  const configContent = fs.readFileSync(configPath, 'utf-8');
  // Extract existing icons from icons: [...] array
  const iconsMatch = configContent.match(/icons:\s*\[([\s\S]*?)\]/);
  if (iconsMatch) {
    const existingIcons = iconsMatch[1]
      .split(',')
      .map((s) => s.trim().replace(/['"]/g, ''))
      .filter((s) => s.length > 0);
    existingIcons.forEach((icon) => iconSet.add(icon));
    console.log(`✓ Loaded ${existingIcons.length} existing icons from monicon.config.ts`);
  }
}

// Extract icon names from ROOM_FACILITIES and COMMON_FACILITIES

// Match all icon: 'icon-name' or icon: 'collection:icon-name' patterns
const iconMatches = typesContent.matchAll(/icon:\s*['"]([^'"]+)['"]/g);
for (const match of iconMatches) {
  let iconValue = match[1];
  // If no collection prefix, add default 'material-symbols:'
  if (!iconValue.includes(':')) {
    iconValue = `material-symbols:${iconValue}`;
  }
  iconSet.add(iconValue);
}

// Additional UI icons (with default collection)
const additionalIcons = [
  'home',
  'location-on',
  'bookmark',
  'chat',
  'person',
  'settings',
  'close',
  'door-open',
];
additionalIcons.forEach((icon) => {
  iconSet.add(`material-symbols:${icon}`);
});

const allIcons = Array.from(iconSet).sort();

console.log(`✓ Found ${allIcons.length} total unique icons (types/index.ts + existing)`);

// Group icons by collection
const iconsByCollection = {};
allIcons.forEach((icon) => {
  const [collection, iconName] = icon.split(':');
  if (!iconsByCollection[collection]) {
    iconsByCollection[collection] = [];
  }
  iconsByCollection[collection].push(iconName);
});

console.log('Collections used:');
Object.keys(iconsByCollection).forEach((collection) => {
  console.log(`  - ${collection}: ${iconsByCollection[collection].length} icons`);
});

// Generate monicon.config.ts
const moniconConfig = `import { reactNative, clean } from '@monicon/core/plugins';
import { MoniconConfig } from '@monicon/core';

export default {
  // Auto-generated icon list
  // - Icons from types/index.ts (facility constants)
  // - Icons from 'npm run add-icon' (preserved during regeneration)
  // Run 'npm run icons' to regenerate after updating types/index.ts
  // Format: 'collection:icon-name' (e.g., 'lucide:home', 'material-symbols:wifi')
  icons: [
${allIcons.map((icon) => `    '${icon}',`).join('\n')}
  ],

  plugins: [
    // Clean output folder before generation
    clean({ patterns: ['components/icons'] }),

    // Generate React Native components
    reactNative({ outputPath: 'components/icons' }),
  ],
} satisfies MoniconConfig;
`;

fs.writeFileSync(path.join(__dirname, '../monicon.config.ts'), moniconConfig);
console.log('✓ Generated monicon.config.ts');

// Generate lib/facilityIcons.ts with support for multiple collections
const iconImports = [];
const iconMappings = [];

allIcons.forEach((fullIcon) => {
  const [collection, iconName] = fullIcon.split(':');
  const pascalCase = iconName
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  const componentName = `${pascalCase}Icon`;

  iconImports.push(`import ${componentName} from '@/components/icons/${collection}/${iconName}';`);
  iconMappings.push(`  '${fullIcon}': ${componentName},`);

  // Also add mapping without collection prefix for backward compatibility
  if (collection === 'material-symbols') {
    iconMappings.push(`  '${iconName}': ${componentName}, // backward compat`);
  }
});

const facilityIconsContent = `// Auto-generated icon mapping for facilities
// This file is generated by scripts/generate-icons.js
// Icons from:
//   - types/index.ts (facility constants)
//   - npm run add-icon (preserved during regeneration)
// DO NOT EDIT MANUALLY - Run 'npm run icons' to regenerate

${iconImports.join('\n')}

// Icon mapping object
// Supports both 'collection:icon-name' and 'icon-name' (default: material-symbols)
export const FACILITY_ICON_MAP: Record<string, React.ComponentType<any>> = {
${iconMappings.join('\n')}
};

// Helper function to get icon component by name
// Accepts 'collection:icon-name' or just 'icon-name' (defaults to material-symbols)
export const getFacilityIcon = (iconName: string) => {
  // Try with prefix first
  if (FACILITY_ICON_MAP[iconName]) {
    return FACILITY_ICON_MAP[iconName];
  }
  // Try with material-symbols prefix as default
  const withPrefix = \`material-symbols:\${iconName}\`;
  return FACILITY_ICON_MAP[withPrefix] || FACILITY_ICON_MAP['material-symbols:home'];
};
`;

fs.writeFileSync(path.join(__dirname, '../lib/facilityIcons.ts'), facilityIconsContent);
console.log('✓ Generated lib/facilityIcons.ts');

console.log('\n✅ Done! Icon configuration updated.');
console.log('📝 Next steps:');
console.log('   1. Restart dev server: npm run dev');
console.log('   2. Icons will be auto-generated by Monicon');
console.log('\n💡 Tip: Icons added via "npm run add-icon" are preserved!\n');
